jdbc.driver=oracle.jdbc.driver.OracleDriver
#jdbc.url=jdbc\:oracle\:thin\:@110.43.196.100\:1521\:ORCL
#jdbc.url=jdbc\:oracle\:thin\:@103.27.6.36\:1521\:ORCL
#jdbc.url=jdbc\:oracle\:thin\:@101.35.112.38\:1521\:ORCL
#jdbc.url=jdbc\:oracle\:thin\:@121.4.148.187\:1521\:ORCL
#jdbc.url=jdbc\:oracle\:thin\:@121.4.148.187\:1521\:ORCL
jdbc.url=jdbc\:oracle\:thin\:@127.0.0.1\:1521\:ORCL
#jdbc.username=wuji_3_8
#jdbc.password=wuji_3_8 æ°æ®åºå¯ç å¯¹çæ²¡ å°±æ¯è¿ä¸ª
jdbc.username=wjtest
#jdbc.password=Admin861808
jdbc.password=wjtest
jdbc.pool.init=5
jdbc.pool.minIdle=3
jdbc.pool.maxActive=500
jdbc.testSql=SELECT 'x' FROM DUAL
server.port=7101
server.register=1
server.area=0001
server.pay=three
server.redis=1
server.lianhua=0
server.redisip=127.0.0.1
server.redisport=6379
server.version=version4564
server.qh=0
server.tablePath=D\:\\HGC\\oracleTable\\
server.tableZone={u"USERANDROLECONTROLRECORD"\:"USERANDROLECONT","IMPORTANTGOODSLU"\:"IMPORTANTGOODSLU"}